---
title: "p8105_hw3_hc3451"
author: "Huanyu Chen"
date: "`r Sys.Date()`"
output: github_document
---

# Problem 1
```{r setup, include=FALSE}
library(p8105.datasets)
data("instacart")
```

This dataset has 1,384,617 rows and 15 variables. This dataset is a Tabular structure with each row representing an order and each column representing an attribute. Key variables include order_id: identifier for the order; aisle_id: identifier for the aisle; product_id: identifier for the product; aisle: name of the aisle; product_name: name of the product, etc.

```{r}
# Number of aisles
num_aisles <- length(unique(instacart$aisle))
print(paste("Number of aisles:", num_aisles))

# Most items
aisle_order_counts <- table(instacart$aisle)
sorted_aisles <- names(sort(aisle_order_counts, decreasing = TRUE))
print("Most items are ordered from: Fresh Vegetable.")
```

```{r}
library(ggplot2)

filtered_aisles <- names(aisle_order_counts[aisle_order_counts > 10000])
filtered_data <- instacart[instacart$aisle %in% filtered_aisles,]
ggplot(filtered_data, aes(x = reorder(aisle, -table(aisle)[aisle]), fill = aisle)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  guides(fill = FALSE) +
  labs(x = "Aisle", y = "Number of Items Ordered", title = "Number of Items Ordered in Each Aisle (Aisles with > 10,000 items)")
```

```{r}
library(dplyr)
library(knitr)

target_aisles <- c("baking ingredients", "dog food care", "packaged vegetables fruits")
filtered_data <- instacart |>
  filter(aisle %in% target_aisles)

product_counts <- filtered_data |>
  group_by(aisle, product_name) |>
  summarise(count = n()) |>
  arrange(aisle, desc(count)) |>
  top_n(3, count)

print("Top 3 Most Popular Items in Each Aisle:")
print(product_counts)
```

```{r}
library(tidyr)

target_products <- c("Pink Lady Apples", "Coffee Ice Cream")
filtered_data <- instacart |>
  filter(product_name %in% target_products)

mean_hour_table <- filtered_data |>
  group_by(product_name, order_dow) |>
  summarise(mean_hour = mean(order_hour_of_day))

mean_hour_pivot <- mean_hour_table |>
  pivot_wider(names_from = order_dow, values_from = mean_hour)
colnames(mean_hour_pivot) <- c("Product Name", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
mean_hour_pivot
```

# Problem 2
```{r}
# Data Cleaning
library(p8105.datasets)
data("brfss_smart2010")

brfss_smart2010 <- janitor::clean_names(brfss_smart2010)
response_order <- c("Poor", "Fair", "Good", "Very good", "Excellent")
brfss_smart2010_health <- brfss_smart2010 |>
  filter(topic == 'Overall Health') |>
  # filter(response == c("Poor", "Fair", "Good", "Very good", "Excellent")) |>
  mutate(response_order = match(response, response_order)) |>
  arrange(response_order)
  # select(response)
write.csv(brfss_smart2010_health, "brfss_smart2010_health.csv", row.names = FALSE)
```

```{r}

```

